### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Vector-Kolesnikoff/grid-template__skills-production#1]
Фон не соответствует
![image](https://user-images.githubusercontent.com/8464662/62322681-46676080-b4ae-11e9-9819-ac511eca8e94.png)

цвет не соответствует
![image](https://user-images.githubusercontent.com/8464662/62322768-7878c280-b4ae-11e9-819d-8bf8389ca484.png)

**Comment by Alecto** [comment]
невалидный код
![image](https://user-images.githubusercontent.com/8464662/62322882-bece2180-b4ae-11e9-9104-a4bdf6eba09c.png)

**Comment by Vector-Kolesnikoff** [comment]
Я же цвета брал с XD макета пипеткой. как так-то..(


чт, 1 авг. 2019 г. в 22:50, Andrey <notifications@github.com>:
